{% set name = "preliz" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6688c6349085c9ef5711ec89c2d8bf53296db6281848f014f50b13fadb55370

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip >=21.3
    - python >=3.10
    - flit
  run:
    - arviz
    - matplotlib-base >=3.5
    - numba >=0.59
    - numpy >=1.22
    - python >=3.10
    - scipy >=1.9.1, <1.13

test:
  imports:
    - preliz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/arviz-devs/preliz
  summary: The place for all your prior elicitation needs.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://preliz.readthedocs.io/

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
