{% set name = "preliz" %}
{% set version = "0.17.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 64c147a55125fde60f0a15a6c35e6ec0aba3ef06fffd303094f45edd8bb5ed01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip >=21.3
    - python {{ python_min }}
    - flit
    - setuptools
  run:
    - matplotlib-base >=3.7
    - numba >=0.59
    - numpy >=1.24
    - python >={{ python_min }}
    - scipy >=1.10, <1.16

test:
  imports:
    - preliz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arviz-devs/preliz
  summary: The place for all your prior elicitation needs.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://preliz.readthedocs.io/

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
