{% set name = "preliz" %}
{% set version = "0.21.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 21b2c8ea25c7781ed89745475510fcc852658668aec25fb89aeac6d6686c996d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip >=21.3
    - python {{ python_min }}
    - flit
    - setuptools
  run:
    - arviz-stats >=0.6.0
    - matplotlib-base >=3.8
    - numba >=0.59
    - numpy >=2.0
    - python >={{ python_min }}
    - scipy >=1.12
test:
  imports:
    - preliz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arviz-devs/preliz
  summary: The place for all your prior elicitation needs.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://preliz.readthedocs.io/

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
