{% set name = "preliz" %}
{% set version = "0.24.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2fa511b9dc534694c9765c489b57cf28f60ee2f5fdf081e098bd70a9efc30bde

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip >=21.3
    - python {{ python_min }}
    - flit
    - setuptools
  run:
    - arviz-stats >=0.6.0
    - matplotlib-base >=3.9
    - numba >=0.62
    - numpy >=2.0
    - pytensor-distributions >=0.1.2
    - python >={{ python_min }}
    - scipy >=1.12
test:
  imports:
    - preliz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arviz-devs/preliz
  summary: The place for all your prior elicitation needs.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://preliz.readthedocs.io/

extra:
  recipe-maintainers:
    - OriolAbril
    - aloctavodia
